In [33]:
import pandas as pd

In [34]:
import numpy as np

In [35]:
data = pd.read_excel("Lab8_data.xlsx")

In [36]:
data

      age  income student credit_rating buys_computer
0    <=30    high      no          fair            no
1    <=30    high      no     excellent            no
2   31…40    high      no          fair           yes
3     >40  medium      no          fair           yes
4     >41     low     yes          fair           yes
5     >42     low     yes     excellent            no
6   31…40     low     yes     excellent           yes
7    <=30  medium      no          fair            no
8    <=30     low     yes          fair           yes
9     >40  medium     yes          fair           yes
10   <=30  medium     yes     excellent           yes
11  31…40  medium      no     excellent           yes
12  31…40    high     yes          fair           yes
13    >40  medium      no     excellent            no

In [39]:
#A1
print("Prior probabilties for each features w.r.t 'buys_computer'\n")

for column in data.columns:

    if column != 'buys_computer':

        print(f"\nPrior Probabilities for {column.upper()}:")

        prior_probabilities = data.groupby(column)['buys_computer'].value_counts(normalize=True)

        print(prior_probabilities)

        print()

print("Prior probabilities for the 'buys_computer' classes\n")

total_instances = len(data)

buys_computer_counts = data['buys_computer'].value_counts()

prior_prob_yes = buys_computer_counts['yes'] / total_instances

prior_prob_no = buys_computer_counts['no'] / total_instances

print(f"Prior probability for buys_computer = 'yes': {prior_prob_yes}")

print(f"Prior probability for buys_computer = 'no': {prior_prob_no}")

Prior probabilties for each features w.r.t 'buys_computer'


Prior Probabilities for AGE:
age    buys_computer
31…40  yes              1.000000
<=30   no               0.600000
       yes              0.400000
>40    yes              0.666667
       no               0.333333
>41    yes              1.000000
>42    no               1.000000
Name: buys_computer, dtype: float64


Prior Probabilities for INCOME:
income  buys_computer
high    no               0.500000
        yes              0.500000
low     yes              0.750000
        no               0.250000
medium  yes              0.666667
        no               0.333333
Name: buys_computer, dtype: float64


Prior Probabilities for STUDENT:
student  buys_computer
no       no               0.571429
         yes              0.428571
yes      yes              0.857143
         no               0.142857
Name: buys_computer, dtype: float64


Prior Probabilities for CREDIT_RATING:
credit_rating  buys_computer
excellent      no               0.50
               yes              0.50
fair           yes              0.75
               no               0.25
Name: buys_computer, dtype: float64

Prior probabilities for the 'buys_computer' classes

Prior probability for buys_computer = 'yes': 0.6428571428571429
Prior probability for buys_computer = 'no': 0.35714285714285715

In [40]:
#A2
for col in ['age', 'income', 'student', 'credit_rating']:
    print(f"\nClass conditional density for {col}:")
    for label in data['buys_computer'].unique():
        density = data[data['buys_computer'] == label][col].value_counts(normalize=True)
        print(f"Class '{label}':\n{density}\n")

Class conditional density for age:
Class 'no':
<=30    0.6
>42     0.2
>40     0.2
Name: age, dtype: float64

Class 'yes':
31…40    0.444444
>40      0.222222
<=30     0.222222
>41      0.111111
Name: age, dtype: float64


Class conditional density for income:
Class 'no':
high      0.4
medium    0.4
low       0.2
Name: income, dtype: float64

Class 'yes':
medium    0.444444
low       0.333333
high      0.222222
Name: income, dtype: float64


Class conditional density for student:
Class 'no':
no     0.8
yes    0.2
Name: student, dtype: float64

Class 'yes':
yes    0.666667
no     0.333333
Name: student, dtype: float64


Class conditional density for credit_rating:
Class 'no':
excellent    0.6
fair         0.4
Name: credit_rating, dtype: float64

Class 'yes':
fair         0.666667
excellent    0.333333
Name: credit_rating, dtype: float64

In [41]:
#A3
import pandas as pd
from scipy.stats import chi2_contingency

df = pd.DataFrame(data)

for feature in df.columns[:-1]:
    for target_feature in df.columns[:-1]:
        if feature != target_feature:
            contingency_table = pd.crosstab(df[feature], df[target_feature])
            chi2, p, _, _ = chi2_contingency(contingency_table)

            alpha = 0.05
            print(f"\nChi-square test for independence between '{feature}' and '{target_feature}':")
            print(f"p-value: {p}")
            if p < alpha:
                print("dependent.")
            else:
                print("independent.")

Chi-square test for independence between 'age' and 'income':
p-value: 0.24295198904422086
independent.

Chi-square test for independence between 'age' and 'student':
p-value: 0.6386770552819057
independent.

Chi-square test for independence between 'age' and 'credit_rating':
p-value: 0.6817807150097924
independent.

Chi-square test for independence between 'income' and 'age':
p-value: 0.24295198904422088
independent.

Chi-square test for independence between 'income' and 'student':
p-value: 0.05881647164242991
independent.

Chi-square test for independence between 'income' and 'credit_rating':
p-value: 0.6944859597510076
independent.

Chi-square test for independence between 'student' and 'age':
p-value: 0.6386770552819057
independent.

Chi-square test for independence between 'student' and 'income':
p-value: 0.05881647164242988
independent.

Chi-square test for independence between 'student' and 'credit_rating':
p-value: 1.0
independent.

Chi-square test for independence between 'credit_rating' and 'age':
p-value: 0.6817807150097924
independent.

Chi-square test for independence between 'credit_rating' and 'income':
p-value: 0.6944859597510076
independent.

Chi-square test for independence between 'credit_rating' and 'student':
p-value: 1.0
independent.

In [42]:
#A4
from sklearn.naive_bayes import GaussianNB

from sklearn.model_selection import train_test_split as tts

from sklearn.preprocessing import LabelEncoder as LE

label_encoder = LE()

data_encoded = data.copy()

for col in data.columns:

    if data[col].dtype == 'object':

        data_encoded[col] = label_encoder.fit_transform(data[col])


X = data_encoded.loc[:, 'age':'credit_rating']

y = data_encoded['buys_computer']

X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=42)

model = GaussianNB()

model.fit(X_train, y_train)

predicted = model.predict(X_test)

print(X_test)

print("\nPredicted classes for test data:")

print(predicted)

    age  income  student  credit_rating
9     2       2        1              1
11    0       2        0              0
0     1       0        0              1

Predicted classes for test data:
[1 0 1]

In [28]:
import pandas as pd

In [29]:
import numpy as np

In [30]:
df=pd.read_csv("train.csv")

In [31]:
df

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5.0,4.0,3.0,4.0,4.0,5.0,5.0,25.0,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1.0,1.0,5.0,3.0,1.0,4.0,1.0,1.0,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5.0,4.0,3.0,4.0,4.0,4.0,5.0,0.0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2.0,2.0,5.0,3.0,1.0,4.0,2.0,11.0,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3.0,3.0,4.0,4.0,3.0,3.0,3.0,0.0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53680,53680,62712,Female,Loyal Customer,38,Business travel,Business,2504,1,1,...,5.0,5.0,5.0,5.0,4.0,5.0,4.0,0.0,0.0,satisfied
53681,53681,52812,Male,disloyal Customer,37,Business travel,Eco,1247,3,3,...,3.0,3.0,4.0,2.0,3.0,3.0,3.0,0.0,13.0,neutral or dissatisfied
53682,53682,27035,Female,Loyal Customer,16,Business travel,Eco Plus,867,4,1,...,4.0,1.0,4.0,3.0,4.0,3.0,4.0,0.0,0.0,neutral or dissatisfied
53683,53683,127523,Male,Loyal Customer,24,Business travel,Business,1009,5,5,...,2.0,5.0,2.0,4.0,3.0,5.0,2.0,6.0,0.0,satisfied
53684,53684,101771,Male,Loyal Customer,53,Business travel,Business,1521,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
target = 'satisfaction'
df.drop(df[df['Gender'] == 'Female'].index, inplace=True)
features = df.drop(columns=[target])
categorical_cols = df.select_dtypes(include=['object']).columns
df[categorical_cols] = df[categorical_cols].astype(str)
features = features.fillna(0)
features = features.fillna('Unknown')
encoder = LabelEncoder()
for col in features.select_dtypes(include=['object']).columns:
    features[col] = encoder.fit_transform(features[col])
X_train, X_test, y_train, y_test = train_test_split(features, df[target], test_size=0.2, random_state=42)
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
accuracy = nb_classifier.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.6131359149582384